ADD:  코멘트 좋아요 기능 구현을 위한 commentlikeview 구현, url 추가
wecode-bootcamp-korea/14-1st-Gotchapedia-backend pull request #15
Opened 2020-11-23 14:46 UTC by devburgundy

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
### 2020.11.23
- 코멘트 좋아요 기능 생성/삭제를 구현 위한 views.py 작성
- 코멘트 좋아요 기능 생성/삭제를 구현 위한 urls.py 작성
		 
## 수정 사항들 자세한 내용
### 2020.11.23
**[url]**  
- http://localhost:8000/comment/like : 댓글 좋아요 생성 (POST)
- http://localhost:8000/comment/like/<int:comment_id> 댓글 좋아요 삭제 (DELETE)

**[코멘트 좋아요 생성]**
- 이미 좋아요를 한 경우 404 에러코드 리턴
- 코멘트가 없을 경우 404 에러코드 리턴
- 좋아요가 생성된경우 201 코드 리턴
- Request Body가 없을 경우 400 에러코드 리턴

**[코멘트 좋아요 삭제]**
- 삭제할 좋아요가 없을 경우 404 에러코드 리턴
- 좋아요 삭제 완료할 경우 204 코드 리턴

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-11-24 13:37 UTC, ulfrid requested changes
데코레이터 변경사항 체크해주시고 코드 수정사항 확인해주세요~!

2020-11-24 13:37 UTC, ulfrid commented on comment/views.py
> +        return JsonResponse (feedback, status=204)
```
         if not like.exists():
             return JsonResponse({"message": "NOT_FOUND"}, status=404)

         like.delete()
         feedback = {
            "message": "SUCCESS"
         }
         return JsonResponse (feedback, status=204)
```
스타일 상으로는 이게 더 흐름이 일정합니다. 코드 작성시 참고해주세요~🙂

2020-11-24 13:37 UTC, ulfrid commented on comment/views.py
> +            user_id    = request.user,
```suggestion
            user_id    = request.user.id,
```

2020-11-24 16:32 UTC, devburgundy commented on comment/views.py
> +        return JsonResponse (feedback, status=204)
넵 확인 후 코멘트 부분과 좋아요 부분 같이 수정했습니다. 감사합니다! 😊

2020-11-24 16:32 UTC, devburgundy commented on comment/views.py
> +            user_id    = request.user,
넵 데코레이터 부분 변경 된 것 확인해서 수정 후 테스트 완료했습니다. 감사합니다!

2020-11-25 06:40 UTC, devburgundy commented
@ulfrid  컨플릭스 해결했습니다. 확인 부탁드리겠습니다 :) 감사합니다.

2020-11-25 08:27 UTC, merged