ADD: models.py 작성 완료
wecode-bootcamp-korea/14-1st-Gotchapedia-backend pull request #3
Opened 2020-11-17 15:13 UTC by gyuseok-dev

- app 분리(users, movie, comment, analysis)
- 앱 별 모델 추가

|app이름|추가된모델|
|------|---|
|users|User|
|movie|Movie, Actor, Genre|
|comment|Comment, Like|
|analysis|Star, User_Log|

2020-11-18 02:08 UTC, soheon-lee commented on analysis/models.py
> +    updated_at = models.DateField(auto_now=True)
코드내에 클래스 단위로, 혹은 함수 단위로 `=`을 기준으로 하여 코드 정렬해주세요

2020-11-18 02:08 UTC, soheon-lee commented on analysis/models.py
> +class User_log(models.Model):
클래스 이름은 띄어쓰기를 할 때 언더바(`_`)를 사용하지 않고 PascalCase를 사용합니다 :)

2020-11-18 02:08 UTC, soheon-lee commented on comment/models.py
> +        related_name = 'main_comment'
`=`을 기준으로 앞뒤로 공백을 주거나 안주거나 괜찮습니다. 그러나 스타일은 통일하시는 것을 추천드립니다.

2020-11-18 02:08 UTC, soheon-lee commented on comment/models.py
> +
Like 테이블 설계 good!
`comment` 오타만 고쳐주세요 ㅎㅎ

2020-11-18 02:08 UTC, soheon-lee commented on movie/models.py
> +    url = models.URLField(max_length=1000)
```suggestion
    movie = models.ForeignKey('Movie', on_delete=models.CASCADE)
    url       = models.URLField(max_length=1000)
```

2020-11-18 02:08 UTC, soheon-lee commented on movie/models.py
> +    movie          = models.ManyToManyField('Movie', through='Movie_Actor')
good !

2020-11-18 02:08 UTC, soheon-lee commented on movie/models.py
> +class Movie_Actor(models.Model):
모든 파일에서 클래스 이름에 간격이 들어간 경우 언더바(`_`) 제거해주시고 PascalCase로 변경해주세요

2020-11-18 02:08 UTC, soheon-lee commented on movie/models.py
> +
깔끔한 코드를 위해 불필요한 공백은 제거해주세요

2020-11-18 02:08 UTC, soheon-lee commented on users/models.py
> +    profile_image  = models.URLField(max_length=1000, null=True)
간격이 얘만 한 칸 나와있네요 ㅎㅎ

2020-11-18 06:37 UTC, soheon-lee commented on movie/models.py
> +        db_table = 'movie_actor'
```suggestion
        db_table = 'movie_actors'
```

2020-11-18 11:34 UTC, jamessoun93 requested changes

2020-11-18 11:34 UTC, jamessoun93 commented on analysis/models.py
> +        db_table = 'user_log'
```suggestion
        db_table = 'user_logs'
```

2020-11-18 11:34 UTC, jamessoun93 commented on movie/models.py
> +    contry       = models.CharField(max_length=200)
column 명 오타 수정해주세요.

2020-11-18 11:34 UTC, jamessoun93 commented on movie/models.py
> +    show_time    = models.IntegerField()
`show_time` 이면 상영시간을 뜻하는 것일텐데 `IntegerField` 로 선언하신 이유가 있나요?

2020-11-18 11:34 UTC, jamessoun93 commented on movie/models.py
> +    movie          = models.ManyToManyField('Movie', through='MovieActor')
```suggestion
    movies          = models.ManyToManyField('Movie', through='MovieActor')
```
M2M 필드 선언해주실때는 헷갈리지않게 복수형으로 선언해주세요.

2020-11-18 11:34 UTC, jamessoun93 commented on movie/models.py
> +    movie = models.ManyToManyField('Movie', through='MovieGenre')
여기도 마찬가지입니다.

2020-11-18 11:34 UTC, jamessoun93 commented on movie/models.py
> +        db_table = 'movie_genre'
```suggestion
        db_table = 'movie_genres'
```

2020-11-18 12:07 UTC, gyuseok-dev commented on movie/models.py
> +    show_time    = models.IntegerField()
나중에 `취향분석페이지`에서 `영화감상시간`으로써 `유저가 별점을 매긴 영화들의 상영시간의 총합`을 구해서 전달할 예정입니다.
show_time의 값은 분단위 정보, 예를 들어 상영시간이 120분이면 120을 넣으려고 해서 `IntergerField` 로 선언하였습니다.

2020-11-19 04:53 UTC, jamessoun93 commented on movie/models.py
> +    show_time    = models.IntegerField()
아하 설명 감사합니다!

2020-11-19 04:53 UTC, jamessoun93 commented
LGTM

2020-11-19 04:53 UTC, merged