Add : views.py 별점 CRUD 구현, 모델 마이그레이션
wecode-bootcamp-korea/14-1st-Gotchapedia-backend pull request #6
Opened 2020-11-19 13:24 UTC by devburgundy

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
-  별점 평가 CRUD 구현
- 로그인 데코레이터는 아직 붙이지 않음 (git에서 받지 못함)
		 
## 수정 사항들 자세한 내용
1. 별점 평가 조회
영화 페이지 조회시 유저가 해당 영화에 별점 평가를 남긴 경우 남긴 별점 점수 조회

2. 별점 평가 생성
영화 페이지에서 영화 평점 생성 시 star 테이블에 별점 생성

3. 별점 평가 수정
영화 페이지에서 유저가 기존에 남긴 영화 평점을 수정할 경우 star 테이블에서 해당 데이터의 정보를 수정

4. 별점 평가 삭제
영화 페이지에서 유저가 기존에 남긴 영화 평점을 삭제할 경우 star 테이블에서 해당 데이터의 정보를 삭제

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-11-19 15:49 UTC, ulfrid requested changes
수정 부탁드립니다.

2020-11-19 15:49 UTC, ulfrid commented on movie/views.py
> +from .models         import *
모델 클래스 개수가 10개가 넘어가지 않는다면 *은 지양해주세요.
```
from module1 import (
		ClassA, 
		ClassB, 
		ClassC, 
		ClassD, 
		ClassE
)
```
위와 같이 임포트해주세요.
참고 위코드 파이썬 코딩컨벤션입니다.
https://www.notion.so/wecode/wecode-Python-Coding-Convention-0bd47a6018634454b9ee1e27984cb83a

2020-11-19 15:49 UTC, ulfrid commented on movie/views.py
> +from anaylsis.models import *
마찬가지입니다.

2020-11-19 15:49 UTC, ulfrid commented on movie/views.py
> +        data = json.loads(reqest.body)
get 메소드에서는 body로 전달받지 않습니다. 
REST API규칙에 위배됩니다.

request.GET.get(movie_id) 와 같은형태로 쿼리스트링을 받을 수 있도록 해주세요,.

2020-11-19 15:49 UTC, ulfrid commented on movie/views.py
> +                return JsonResponse({"message":"NOT_FOUND"}, status = 404)
로직이 잘못된것 같은데, star가 담겼다면 첫번째를 찾고, 포인트를 찾은뒤, NOT_FOUND에러가 리턴되는 이유가 궁금합니다.

2020-11-19 15:49 UTC, ulfrid commented on movie/views.py
> +            return JsonResponse(feedback, status = 200)
이부분의 로직도 다시 확인해주세요.

2020-11-19 15:49 UTC, ulfrid commented on movie/views.py
> +        data = json.loads(reqest.body)
delete 도 마찬가지로 body로 데이터를 전송받지 않습니다. get과 같이 쿼리스트링을 확인해주세요.

2020-11-19 15:49 UTC, ulfrid commented on movie/views.py
> +
로직도 확인해 주세요.

2020-11-19 16:12 UTC, devburgundy commented on movie/views.py
> +from .models         import *
수정하겠습니다. 감사합니다.

2020-11-19 16:12 UTC, devburgundy commented on movie/views.py
> +from anaylsis.models import *
수정하겠습니다. 감사합니다.

2020-11-19 16:13 UTC, devburgundy commented on movie/views.py
> +        data = json.loads(reqest.body)
수정하겠습니다. 감사합니다.

2020-11-19 16:14 UTC, devburgundy commented on movie/views.py
> +                return JsonResponse({"message":"NOT_FOUND"}, status = 404)
else 구문이 들어가는게 맞는데 빠진 것 같습니다. 수정하겠습니다. 감사합니다.

2020-11-19 16:14 UTC, devburgundy commented on movie/views.py
> +            return JsonResponse(feedback, status = 200)
수정하겠습니다. 감사합니다.

2020-11-19 16:15 UTC, devburgundy commented on movie/views.py
> +
수정하겠습니다. 감사합니다.

2020-11-19 16:15 UTC, devburgundy commented on movie/views.py
> +        data = json.loads(reqest.body)
수정하겠습니다. 감사합니다.

2020-11-21 05:49 UTC, ulfrid requested changes

2020-11-21 05:49 UTC, ulfrid commented on movie/urls.py
> +    path('star/create', CreateStarView.as_view()),
메소드만 잘 정리하셔도 클래스 하나에 경로 하나면 됩니다. 
REST API 규칙에 어긋난 경로네요. 미리 파악 못해드려서 죄송합니다.

2020-11-21 12:26 UTC, devburgundy commented on movie/urls.py
> +    path('star/create', CreateStarView.as_view()),
수정했습니다. 주말임에도 불구하고 리뷰 달아주셔서 감사합니다 지훈님 ㅠㅠ

2020-11-23 14:32 UTC, ulfrid requested changes
확인 바랍니다!🙂

2020-11-23 14:32 UTC, ulfrid commented on analysis/views.py
> +
이런식의 처리는 당장은 문제없겠지만 추후에 확장성에 문제가 됩니다. class를 나누었으면 좋겠습니다.
인자를 받는 메소드들을 그룹해서 StarDetailView 로 해주세요.

2020-11-23 15:13 UTC, devburgundy commented on analysis/views.py
> +
수정하겠습니다. 감사합니다 :-)

2020-11-24 01:06 UTC, ulfrid commented
LGTM.

2020-11-24 01:06 UTC, merged