Feature/star
wecode-bootcamp-korea/14-1st-Gotchapedia-backend pull request #8
Opened 2020-11-20 13:13 UTC by yj-leee

## 수정 사항 간략한 한줄 요약
- 별점(0.5점~5점까지)의 개수 카운트 view 추가

## 수정 사항들 자세한 내용
- analysis 앱 StarratingView 추가 / postman 테스트 완료

- movie
영화 상세 페이지에서 각각의 영화에 대해 유저들이 평가한 별점의 개수 리턴 
-users
유저 개인 페이지에서 모든 영화에 대해 평가한 별점의 개수 리턴

## 기타 질문 및 특이 사항
-효율성
movie, user 사용하는 페이지가 다른데 view를 두개로 나누는게 좋을까요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-11-23 14:25 UTC, ulfrid requested changes
우선 이부분들 수정 부탁드립니다.

2020-11-23 14:25 UTC, devops-andrew commented on users/utils.py
> +            request.user  = user.id
id를 넘기기보다는 객체를 넘겨주세요.
```suggestion
            request.user  = user
```

2020-11-23 14:25 UTC, devops-andrew commented on analysis/views.py
> +        if request.GET.get('id', None) != None:
```suggestion
         ???_id  = request.GET.get('id', None) 
        if ???_id:
```
위의 id는 어떤 아이디 일까요? 영화 id 인가요? 
제대로 담기고 None이 아니라면 True 이므로 != None 할 필요 없습니다.

2020-11-23 14:25 UTC, devops-andrew commented on analysis/views.py
> +            movie_id       = request.GET.get('id', None)
위에서 받았다면 여기서 또 받을 필요가 없겠죠

2020-11-23 14:25 UTC, ulfrid commented on analysis/urls.py
> +from analysis.views import StarratingView
```suggestion
from analysis.views import StarRatingView
```

2020-11-23 14:25 UTC, ulfrid commented on analysis/urls.py
> +    path("/my_star", StarratingView.as_view()),
```suggestion
    path("/my_star", StarRatingView.as_view()),
```

2020-11-23 14:25 UTC, ulfrid commented on analysis/views.py
> +class StarratingView(View):
```suggestion
class StarRatingView(View):
```

2020-11-23 15:13 UTC, yj-leee commented
[](url)
<img width="1113" alt="스크린샷 2020-11-23 오후 11 51 35" src="https://user-images.githubusercontent.com/70866485/99978838-c9ba6d00-2de9-11eb-9633-4331824e5e47.png">
<img width="1140" alt="스크린샷 2020-11-23 오후 11 51 21" src="https://user-images.githubusercontent.com/70866485/99978863-cd4df400-2de9-11eb-96f9-f3fd459523f6.png">
<img width="698" alt="스크린샷 2020-11-23 오후 11 52 03" src="https://user-images.githubusercontent.com/70866485/99978871-d048e480-2de9-11eb-8611-5c10c1a91482.png">
<img width="685" alt="스크린샷 2020-11-23 오후 11 52 38" src="https://user-images.githubusercontent.com/70866485/99978876-d212a800-2de9-11eb-9c22-b2bace10ed99.png">
테스트 파일 추가

2020-11-23 15:13 UTC, yj-leee commented
<img width="1140" alt="스크린샷 2020-11-23 오후 11 51 21" src="https://user-images.githubusercontent.com/70866485/99978938-e8b8ff00-2de9-11eb-947f-f09b25c7deee.png">

2020-11-23 15:15 UTC, yj-leee commented
![Uploading 스크린샷 2020-11-23 오후 11.51.35.png…]()

2020-11-24 01:50 UTC, ulfrid commented
LGTM

2020-11-24 01:50 UTC, merged