ADD: movie app 영화 정보 출력을 위한 view 작성, url 수정
wecode-bootcamp-korea/14-1st-Gotchapedia-backend pull request #9
Opened 2020-11-20 13:57 UTC by devburgundy

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 영화 상세 페이지에 출력할 영화 정보 및 배우/감독 정보 views.py 구현
- 영화 평점 내용 제외
- 영화 상세 페이지 urls.py 구현
		 
## 수정 사항들 자세한 내용
GET 메소드 사용하여 아래 내용 출력

**[영화 정보]**
- 영화 ID
- 영화 이름
- 영화 제작 국가
- 영화 설명
- 영화 개봉일
- 영화 러닝타임
- 영화 장르 
- 영화 메인 이미지
- 영화 서브 이미지 

**[배우/감독 정보]**
- 감독/배우 이름
- 감독/배우 프로필 이미지
- 감독/배우 포지션

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-11-23 04:23 UTC, ulfrid requested changes
확인부탁드립니다.

2020-11-23 04:23 UTC, ulfrid commented on movie/views.py
> +            staff_list = []
https://stackoverflow.com/questions/4260280/if-else-in-a-list-comprehension 를 참고해보시고
list comprehension  에 if  스테이트를 걸어서 코드 단축을 해주세요.

2020-11-23 04:42 UTC, devburgundy commented on movie/views.py
> +            staff_list = []
수정하겠습니다. 감사합니다.

2020-11-24 03:33 UTC, devburgundy commented
@ulfrid 수정 완료했습니다. 감사합니다 :-)

2020-11-24 04:37 UTC, ulfrid commented
LGTM을 드립니다! 👍

2020-11-24 04:37 UTC, merged